---
title: ""
output: 
  html_document:
    toc: false
    number_sections: false
---

# Contact Information

- **Name:** Brianna Carnagie
- **Address:** New York, NY
- **Phone:** 347-319-4749
- **Email:** bac2214@columbia.edu
- **LinkedIn:** [linkedin.com/in/briannacarnagie](https://www.linkedin.com/in/briannacarnagie)

# Education

## Columbia University Mailman School of Public Health
*Expected May 2024*  
- Master of Public Health in Epidemiology  
- Certificate in Applied Biostatistics and Public Health Data Science  
- **Relevant Coursework:** Applied Regression I, Analysis of Categorical Data, Data Science I, Relational Databases and SQL Programming, Public Health GIS, Epidemiology II & III, Application of Epidemiological Research Methods.   

## Stony Brook University
*May 2022*  
- Bachelor of Science in Health Science  
- Concentration in Public Health  
- Health, Medicine, and Society Minor  
- **GPA:** 3.72  

# Professional Experience

## ICAP at Columbia University  
*New York, NY*  
Data Assistant  
- *August 2023 – Present*  
  * Leveraged statistical programming in SAS to conduct data monitoring and analysis, increasing report accuracy by 20%.  
  * Streamlined data management processes by assisting with the cleaning of over 30 datasets and updating 10+ documentation files, including data dictionaries and SOPs, leading to a 15% improvement in data integrity and usability.  
  * Conducted an extensive literature review of over 20 sources on the social determinants of HIV in Africa, identifying 20 key factors and contributing to the development of 5 new research hypotheses which drove project direction.  

## Wellness Together
*Roseville, CA*   
Partnerships Assistant     
- *June 2022 – Present* 
  * Developed and implemented the first-ever monthly workshop workflow model for Mind Out Loud, a pioneering program aimed at equipping high school students with the necessary tools and resources for youth mental health advocacy.    
  * Led the External Relations Committee, mentoring students and offering expertise in partnership development, thereby enhancing their ability to cultivate meaningful community relationships and positively impacting the program's success.  
  * Cultivated six new organizational partners for 2022-2023 school year, successfully raising program funding by 35%.    
  * Significantly improved program participation by spearheading first-ever affiliate mentorship program for 27 student participants, with a 90% satisfaction rating among 11 Affiliate Mentors.    

## Columbia University, Office of Education Initiatives
*New York, NY*   
- SPHSP Teaching Assistant   
- *May 2023 – August 2023*
  * Acted as a TA for the SPHSP program, providing academic support and guidance to a cohort of 34 undergraduate students interested in public health careers.  
  * Provided personalized mentoring and guidance to 7 students, meeting with students weekly to help them clarify their career goals and make informed decisions about their academic and professional paths post-graduation.  
  * Coordinated 7 educational events, including guest lectures, seminars, and workshops, featuring prominent public health leaders and experts at Columbia University Mailman School of Public Health.
  * Served as an evaluator for poster presentations created by SPHSP students, ensuring the quality and relevance of their research projects that were later presented at the CDC at the conclusion of the program.  

## Columbia University, Office of Diversity and Multicultural Affairs
*New York, NY*   
- SPREP Administrative Facilitator   
- *November 2022 – June 2023*   
  * Coordinated and facilitated 12 workshops for over 300 middle and high school students interested in the sciences and health professions, providing them with exposure to these fields and enhancing their academic interests.  
  * Utilized strong organizational and administrative skills to manage logistics and scheduling, ensuring the successful execution of program sessions with a 92% satisfaction rate as per a post program survey distributed to student participants.  
  * Conducted 1:1 sessions with 30 high school seniors enrolled in the program to provide personalized mentorship, assisting them in refining their career goals and developing strong academic and professional strategies for their future endeavors.  

## Stony Brook University, Department of Applied Mathematics and Statistics
*Stony Brook, NY*   
- Undergraduate Teaching Assistant 
- *August 2020 – December 2020*   
  * Provided academic support to 20 students enrolled in AMS 110, a course focused on probability theory and statistical techniques with applications to life sciences.  
  * Held 5 office hours per week, assisting an average of 3 students during each session, ensuring prompt assistance and fostering a supportive learning environment.  

## Stony Brook University, Center for Excellence in Learning and Teaching
*Stony Brook, NY*     
- Student Office Assistant     
- *January 2022 – May 2022*     
  * Assisted in organizing and coordinating 4 workshops and events to facilitate faculty development in teaching practices.  
  * Offered administrative support by assisting faculty members in setting up appointments and consultations with the CELT team, streamlining the process and improving accessibility to resources.  
  * Actively contributed to CELT's online presence by creating and posting engaging social media content on Instagram and Twitter, resulting in a 20% increase in online engagement and followership for the Spring 2022 academic year.  

## NYC Health and Hospitals
*New York, NY*  
- Contact Tracer  
- *June 2020 – June 2021*  
  * Placed and fielded calls to approximately 40-50 NYC residents per day and provided contacts with approved information about isolation procedures, accurately identifying COVID-19 cases and contacts.
  * Utilized data analysis and reporting tools to track and monitor the progress of contact tracing efforts, identifying trends and patterns that contributed to the development of more effective strategies for controlling the spread of the virus.  
  * Collaborated and coordinated with a team of 30 public health professionals to efficiently complete contact notification and monitoring assignments, reducing community transmission of COVID-19.  

## Manhattan Hematology Oncology Associates
*New York, NY*  
- Medical Receptionist  
- *June 2019 – January 2020*  
  * Proficiently utilized Electronic Medical Records (EMR) software to organize and maintain patient records, ensuring strict adherence to HIPAA regulations and safeguarding patient confidentiality.   
  * Demonstrated exceptional organizational skills by efficiently managing office and medical supply inventories, including the receipt of deliveries and the meticulous organization of supplies in stockrooms and examination rooms.  
  * Effectively handled a high volume of communication by professionally answering and directing over 30 incoming phone calls daily from patients and healthcare providers, contributing to seamless clinic operations.  

## Integrated Quality Care Medical
*Queens, NY*  
- Medical Receptionist  
- *July 2018 – January 2019*  
  * Greeted and checked-in patients and collected personal, medical, and insurance information.  
  * Scheduled and verified patient appointments and scheduled appointments with secondary care providers.
  * Coordinated physician schedules and maintained patient flow by communicating patient arrivals or delays.  

# Internships

## ICAP at Columbia University
*New York, NY*  
- Next Generation Intern  
- *May 2023 – August 2023*  
  * Supported a cross-sectional research study involving 600+ PLHIV, evaluating SARS-CoV-2 seroprevalence and the impact of COVID-19 in Africa.  
  * Utilized SAS software to analyze and interpret data from 2 study sites, focusing on COVID-19 vaccine uptake, risk factors, and treatment access among PLHIV.  
  * Prepared a final report for the CDC, which included the creation of nine data tables, highlighting key findings that informed recommendations for improving public health initiatives and potentially impacting thousands of PLHIV.  

## Emblem Health  
*New York, NY*  
- Summer Associate  
- *June 2023 – August 2023*  
  * Leveraged advanced data analysis techniques in Microsoft Excel to evaluate community feedback and complex health data, playing an instrumental role in assessing community health needs.  
  * Translated complex data findings into easily understandable insights for community stakeholders, facilitating data-driven decision-making in the implementation of community health interventions.  
  * Successfully planned and executed 3 health screening events across the NYC Metropolitan area, demonstrating exceptional project management and organizational skills, and impacting thousands of community members.  

## Northwell Health
*New Hyde Park, NY*  
- Healthcare Management Summer Associate  
- *June 2021 – August 2021*  
  * Developed a volume reallocation plan for an operating room anticipating reconstruction, coordinating transfer of over 200 surgical procedures to alternative hospitals in the region.  
  * Analyzed REDCap database of over 6,000 clinical records, optimizing charge capture of drugs utilized during surgical cardiac procedures using Microsoft Access.  
  * Collaborated with 2 project managers to launch the first-ever employee appreciation week, increasing employee engagement by 35%.  

## The Humanology Project
*Stony Brook, NY*  
- Campus Outreach Intern  
- *August 2020 – May 2022*  
  * Assist with the planning and coordination of workshops and events off-campus.  
  * Identify possible community partnership and education opportunities with local clubs and organizations on campus.  
  * Work directly with executive board to support overall project needs.  

# Research and Projects

## Food Insecurity and Educational Attainment  
*November 2023*  
- Data Visualization Project  
  * Created a series of maps in QGIS comparing the relationships between food insecurity rates and educational attainment levels in elementary school students attending public schools in New York City.  
  * Ran a spatial regression analysis in RStudio to examine the spatial autocorrelation and identify significant predictors that influence the relationship between food insecurity rates and educational attainment levels, offering a deeper understanding of the spatial patterns and potential drivers of these socioeconomic factors.  

## Epidemiology Masters Student Day
*October 2023*  
- Poster Presentation  
  * Carnagie, B.A., Greenleaf, A., Howard, A.A. (2023). "Exploring COVID-19 Impacts and Vaccine Uptake Among People Living with HIV in Western Kenya." Poster presented at Columbia University Epidemiology Student Poster Presentation.  
    + Utilized SAS to run logistic regressions to assess the association between sociodemographic variables and COVID-19 vaccine uptake, contributing valuable insights into the factors influencing vaccination decisions among this vulnerable population.  

## Youth Mental Health Advocacy Organizations Report
*July 2023*  
- Competitive Analysis Slide Deck  
  * Conducted extensive research to identify and evaluate youth mental health advocacy organizations, examining their missions, programs, and impact.  
  * Analyzed the effectiveness of these organizations in addressing youth mental health challenges, identifying best practices and areas for improvement.  
  * Presented the report to stakeholders and decision-makers, fostering discussions on strategies to enhance youth mental health support and unique advocacy initiatives.  

## Stony Brook Health Science Student Poster Presentation
*December 2021*  
- Poster Presentation  
  * Carnagie, B.A. (2021). "A Qualitative Phenomenological Research Study Exploring the Perceptions of African American Adolescents Regarding Food Insecurity in Urban Communities of New York City." Poster presented at Stony Brook University Health Science Student Full Poster Presentation.  
    + Demonstrated a comprehensive understanding of ethical research practices by actively drafting an IRB protocol proposal for the research project. This proposal encompassed a thorough literature review, a detailed methods section, and a comprehensive assessment of potential harm to participants.  

# Technical Skills

* **Coding Languages and Skills:** Excel (Advanced), R (Intermediate), SAS (Intermediate), QGIS   (Intermediate), Tableau (Beginner), SQL (Beginner), ArcGIS (Beginner) 
* **R Packages and Skills:** {ggplot2}, {tidyverse}, {lubridate} 
* **Analysis Skills:** linear and logistic regression, data wrangling, data visualization, exploratory data analysis, geospatial analysis, geospatial mapping   

# Certfications

* Certified Health Education Specialist (CHES)  
* Youth Mental Health First Aid   

